### ISSUE TITLE
Can we enable program to generate only the report from existing log files and test-suite inputs (basically should skip execution of script).

### ISSUE THREAD

**Issue by rajeshgrs** [rajeshgrs/dq-cli#40]
Hi @jeevanjagadeesh ,

Can we enable program to generate only the report from existing log files and test-suite inputs (basically should skip execution of script).

Looking for some command argument option that will decide whether script should execute the shell/batch script or not. In either case, program should be able to generate report based on given test suite (-src oie_rtm -gp config.json) and available log files under /output/cli_logs for corresponding test-cases in test-suite.

**Comment by jeevanjagadeesh** [comment]
Rajesh,

Looks like the script execution was stopped due to timeout.  
ExecutionTimeout is set to 30 mins, so after 30 mins, childProcess.exec killed the process. Therefore the failure message
Can you increase the timeout to 1hour and re-run the same scripts?


Logs --

"stderr":"dos2unix: converting file /export/home/dq90_qa/dqcli_1020/output/executables/oie_rtm.sh to UNIX format ...\n",
"msg":" Execution done","time":"2017-06-15T06:14:15.466Z","v":0}


"err":{"killed":false,"code":255,"signal":null,"cmd":"/export/home/dq90_qa/dqcli_1020/output/executables/oie_rtm.sh"},
"msg":"Error in executing file","time":"2017-06-15T06:45:10.722Z","v":0}

**Comment by rajeshgrs** [comment]
Hi @jeevanjagadeesh ,
   Timeout has been set to pretty high number "ExecutionTimeout" : 2800000. 
Sorry I should have sent this details to you before itself. I have attached the property file used
[1020_irl64dqd04.zip](https://github.com/rajeshgrs/dq-cli/files/1080554/1020_irl64dqd04.zip)

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs ,

Fixed this issue. Please validate. Another parameter needs to be passed to the script, if the script execution needs to be skipped and report needs to be generated from logs.

Default value of se = N - if value not passed, script will be executed and then report generation

node dq_cli.js -src TestSuiteOIERTM -gp config.json -se Y

**Comment by rajeshgrs** [comment]
Ok Great. Thanks Jeevan. I will check it out today.

Regards,
Rajesh

**Comment by rajeshgrs** [comment]
Hey Jeevan, Thanks much. It is working perfectly fine.

**Comment by jeevanjagadeesh** [comment]
Cool... Closing this issue... If you face the issue again, do share the logs, let me checkout the reason.
